const fake_data = [
    {
        serial: "S0000000001",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000002",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000003",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000004",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000005",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000006",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000007",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000008",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000001",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000002",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000003",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000004",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000005",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000006",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000007",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
    {
        serial: "S0000000008",
        product: "DSD 4138 MCS 12P",
        curr_status: "CA Test Failed",
        target_status: "Mechanical",
        user: "bhanu.pratap",
    },
];

export default fake_data;
